# Generated by Django 3.1.4 on 2021-05-30 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlserverconnect', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertdata',
            name='isactive',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='insertdata',
            name='presentclass',
            field=models.IntegerField(null=True),
        ),
    ]
