# Generated by Django 3.1.4 on 2021-05-30 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlserverconnect', '0002_auto_20210530_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='insertdata',
            name='section',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='insertdata',
            name='isactive',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
