# Generated by Django 3.1.4 on 2021-06-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sqlserverconnect', '0003_auto_20210530_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insertdata',
            name='presentclass',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
